# Clarifications

> Generated by the specification-agent when genuine ambiguities are detected during `/plan`.
> Fill in the `**Resolved:**` fields below, then re-run `/planr-pipeline:plan {slug}` — the agent will read your answers and decompose without guessing.

---

## Clarification 1: <short question>

**Context:** <why this is ambiguous — what the spec says vs what it could mean>

| Option | Description | Trade-off |
|---|---|---|
| A | <description> | <pros / cons> |
| B | <description> | <pros / cons> |

**Recommended:** <A or B>
**Resolved:** _<PO fills this in — write the letter and a brief justification>_

---

<!-- Copy the block above for additional clarifications. -->
