# {{AppName}} — Project Snapshot

> Auto-generated by `/openplanr-pipeline:snapshot`. Do not edit manually.
> Run `/openplanr-pipeline:snapshot` (or trigger it via `/dev-phase`) to refresh.

---

## Project Identity

| Field             | Value                          |
|-------------------|--------------------------------|
| Project Name      | `{{AppName}}`                  |
| Database Type     | `{{DatabaseType}}`             |
| Primary Stack     | `{{Language}} / {{Framework}}` |
| ORM               | `{{ORM}}`                      |
| Last Updated      | `{{Timestamp}}`                |
| Plugin Version    | openplanr-pipeline v{{PluginVersion}} |

---

## Phase Status

| Phase     | Status | Last Run       | Notes                       |
|-----------|--------|----------------|-----------------------------|
| DB Prep   | `[ ]`  | —              | `output/db/schema.json`     |
| PO Phase  | `[ ]`  | —              | per-feature decomposition   |
| DEV Phase | `[ ]`  | —              | per-feature code generation |

---

## Feature Registry

| Feature      | US Count | Task Count | Design Spec | PO Status | DEV Status | Notes |
|--------------|----------|------------|-------------|-----------|------------|-------|
| feat-{name}  | —        | —          | no          | pending   | pending    | —     |

---

## Active Agents

> Subagents shipped by the openplanr-pipeline plugin. See `${CLAUDE_PLUGIN_ROOT}/docs/agent-model-map.md`.

| Agent                | Model            | Phase     | Last Invoked | Status |
|----------------------|------------------|-----------|--------------|--------|
| db-agent             | claude-sonnet-4-6 | 0.1      | —            | idle   |
| designer-agent       | claude-sonnet-4-6 | 1        | —            | idle   |
| specification-agent  | claude-sonnet-4-6 | 1        | —            | idle   |
| frontend-agent       | claude-opus-4-7   | 3        | —            | idle   |
| backend-agent        | claude-opus-4-7   | 0.2 + 3  | —            | idle   |
| qa-agent             | claude-sonnet-4-6 | 3.5      | —            | idle   |
| devops-agent         | claude-sonnet-4-6 | 3.5      | —            | idle   |
| doc-gen-agent        | claude-sonnet-4-6 | 3.5      | —            | idle   |

---

## Build Log

```
[append-only — /snapshot adds events here per run; never truncate]
```

---

## Known Issues / Escalations

```
[populated from output/feats/feat-*/us-*/tasks/error-report.md files]
[items that exceeded 3 correction iterations per docs/rules.md R6]
```

---

## Stack Summary

```yaml
[full content of input/tech/stack.md embedded here at snapshot time]
```

---

## How to Use This File

All subagents read `CLAUDE.md` at the start of each invocation to understand:
- Current phase status (don't redo completed work)
- Feature registry (don't conflict with prior outputs)
- Known issues (don't repeat failed task patterns)
- Active stack (use the right conventions)

Per `${CLAUDE_PLUGIN_ROOT}/docs/rules.md` R7, this file MUST be current before any subsequent agent run.

---

## Planning Mode

This file is owned by **openplanr-pipeline** (the spec-driven mode). If your project also uses **planr** CLI for agile planning (epic/feature/story/task hierarchy), see `.planr/CLAUDE.md` for that system's context-gathering protocol. The two systems coexist — they don't conflict because they own different files.

---

*Generated by: `/openplanr-pipeline:snapshot` · See `${CLAUDE_PLUGIN_ROOT}/skills/snapshot/SKILL.md`.*
