export const ARTIFACT_ERROR_CODES = Object.freeze({
  INPUT_INVALID: 'E_ARTIFACT_INPUT_INVALID',
  FILE_MISSING: 'E_ARTIFACT_FILE_MISSING',
  ROOT_MISSING: 'E_ARTIFACT_ROOT_MISSING',
  PATH_TRAVERSAL: 'E_ARTIFACT_PATH_TRAVERSAL',
  SYMLINK_ESCAPE: 'E_ARTIFACT_SYMLINK_ESCAPE',
  EXTERNAL_ASSET: 'E_ARTIFACT_EXTERNAL_ASSET',
  UNRESOLVED_ASSET: 'E_ARTIFACT_UNRESOLVED_ASSET',
  UNSUPPORTED_MODULE: 'E_ARTIFACT_UNSUPPORTED_MODULE',
  UNSAFE_HTML: 'E_ARTIFACT_UNSAFE_HTML',
  FILE_LIMIT: 'E_ARTIFACT_FILE_LIMIT',
  BYTE_LIMIT: 'E_ARTIFACT_BYTE_LIMIT',
  OUTPUT_LIMIT: 'E_ARTIFACT_OUTPUT_LIMIT',
  REDACTION: 'E_ARTIFACT_REDACTION',
  ENVELOPE_INVALID: 'E_ARTIFACT_ENVELOPE_INVALID',
  SCHEMA_UNSUPPORTED: 'E_ARTIFACT_SCHEMA_UNSUPPORTED',
  LOOPBACK_BIND: 'E_ARTIFACT_LOOPBACK_BIND',
  LOOPBACK_STATE: 'E_ARTIFACT_LOOPBACK_STATE',
  PORT_IN_USE: 'E_ARTIFACT_PORT_IN_USE',
  SESSION_TOKEN: 'E_ARTIFACT_SESSION_TOKEN',
  SESSION_NOT_FOUND: 'E_ARTIFACT_SESSION_NOT_FOUND',
  REQUEST_INVALID: 'E_ARTIFACT_REQUEST_INVALID',
  REQUEST_LIMIT: 'E_ARTIFACT_REQUEST_LIMIT',
  SANDBOX_POLICY: 'E_ARTIFACT_SANDBOX_POLICY',
  BRIDGE_INVALID: 'E_ARTIFACT_BRIDGE_INVALID',
  REVIEW_INVALID: 'E_ARTIFACT_REVIEW_INVALID',
  REVIEW_WRITE: 'E_ARTIFACT_REVIEW_WRITE',
  REVIEW_IMPORT: 'E_ARTIFACT_REVIEW_IMPORT',
  REVIEW_DECODER_REQUIRED: 'E_ARTIFACT_REVIEW_DECODER_REQUIRED',
  REVIEW_EXPORT: 'E_ARTIFACT_REVIEW_EXPORT',
  DIGEST_MISMATCH: 'E_ARTIFACT_DIGEST_MISMATCH',
  STALE_REVIEW: 'E_ARTIFACT_STALE_REVIEW',
  MERGE_CONFLICT: 'E_ARTIFACT_MERGE_CONFLICT',
  CODEC_INVALID: 'E_ARTIFACT_CODEC_INVALID',
  CODEC_UNAVAILABLE: 'E_ARTIFACT_CODEC_UNAVAILABLE',
  CODEC_FAILED: 'E_ARTIFACT_CODEC_FAILED',
  FRAGMENT_INVALID: 'E_ARTIFACT_FRAGMENT_INVALID',
  FRAGMENT_VERSION_UNSUPPORTED: 'E_ARTIFACT_FRAGMENT_VERSION_UNSUPPORTED',
  FRAGMENT_TOO_LARGE: 'E_ARTIFACT_FRAGMENT_TOO_LARGE',
  DECOMPRESSION_LIMIT: 'E_ARTIFACT_DECOMPRESSION_LIMIT',
  BROWSER_UNSUPPORTED: 'E_ARTIFACT_BROWSER_UNSUPPORTED',
  ENCRYPTION_FAILED: 'E_ARTIFACT_ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'E_ARTIFACT_DECRYPTION_FAILED',
  CONFIRMATION_REQUIRED: 'E_ARTIFACT_CONFIRMATION_REQUIRED',
  SHORT_CONFIRMATION_REQUIRED: 'E_ARTIFACT_SHORT_CONFIRMATION_REQUIRED',
  PASTE_INVALID: 'E_ARTIFACT_PASTE_INVALID',
  PASTE_UNAVAILABLE: 'E_ARTIFACT_PASTE_UNAVAILABLE',
  PASTE_EXPIRED: 'E_ARTIFACT_PASTE_EXPIRED',
  PASTE_LIMIT: 'E_ARTIFACT_PASTE_LIMIT',
  SHARE_NETWORK: 'E_ARTIFACT_SHARE_NETWORK',
  ROOM_INVALID: 'E_ARTIFACT_ROOM_INVALID',
  ROOM_UNAVAILABLE: 'E_ARTIFACT_ROOM_UNAVAILABLE',
  ROOM_EXPIRED: 'E_ARTIFACT_ROOM_EXPIRED',
  ROOM_CLOSED: 'E_ARTIFACT_ROOM_CLOSED',
  ROOM_FORBIDDEN: 'E_ARTIFACT_ROOM_FORBIDDEN',
  ROOM_EVENT_INVALID: 'E_ARTIFACT_ROOM_EVENT_INVALID',
  ROOM_EVENT_REPLAY: 'E_ARTIFACT_ROOM_EVENT_REPLAY',
});

export class PipelineError extends Error {
  constructor(code, message, fix = '', details = undefined) {
    super(message);
    this.name = 'PipelineError';
    this.code = code;
    this.fix = fix;
    if (details !== undefined) this.details = details;
  }

  toJSON() {
    return {
      ok: false,
      code: this.code,
      problem: this.message,
      ...(this.fix ? { fix: this.fix } : {}),
      ...(this.details === undefined ? {} : { details: this.details }),
    };
  }
}
